.PHONY: clean All

All:
	@echo "----------Building project:[ NumOfWords - Debug ]----------"
	@cd "NumOfWords" && "$(MAKE)" -f  "NumOfWords.mk"
clean:
	@echo "----------Cleaning project:[ NumOfWords - Debug ]----------"
	@cd "NumOfWords" && "$(MAKE)" -f  "NumOfWords.mk" clean
